language: python
cache: pip
python:
- 3.6
before_install:
- sudo apt-get update
- sudo apt-get install libsqlite3-dev
- sudo apt-get install build-essential
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda update --yes -q conda
- conda config --set always_yes true
- conda config --set anaconda_upload no
- conda config --add channels conda-forge
install:
- conda install -q python=$TRAVIS_PYTHON_VERSION ncurses pip requests conda-build
  jinja2 anaconda-client nose Cython peewee
- pip install Cython
- pip install 'peewee>=3.0'
- pip install -r requirements.txt
- pip install codecov 'coverage==4.3' codeclimate-test-reporter
script:
- nosetests --with-coverage --cover-erase --cover-package=decide --cover-inclusive
after_success:
- bash <(curl -s https://codecov.io/bash)
- CODECLIMATE_REPO_TOKEN=38338f4be02599584d9d3672ed50c25ca2b24c0a9565bfbb000e6a1389f13700
  codeclimate-test-reporter
- chmod +x ./deploy_anaconda.sh
deploy:
  - provider: script
    script: "./deploy_anaconda.sh"
    on:
      tags: true
    skip_cleanup: true
  - provider: pypi
    user: jelmert
    password:
      secure: fmCoyxAZjjMM231CWnHqH3sbccEtBOklO00zztQXdHuNLkN0qk6jfkuU1CUD663tVPV75PCkhtr8CAXPTZ9vRR9gai3B4+IaJWUowdEL/c8wj7iilEixRlG2IdnXrI61dz/tMgRtq3pEzwDmdCvTfJaOUK2aAtocMKOC+74N/xh66sOCijbXBBdEE2x1tYjw1DhhoymHgAfYUjRU4rBKjSCrF3ZakeWGFhNeD66g/LzJh30MfT4Zzs5xHCEsRayVeKfYlBpmlvUOE+loPwdulGKEg2hYmOR566tKgYc0XGqlhepMIeFWMDwAyoXbsg9frTiVWgL3jdtIXQ2uQ7TqKjK8sIy28XFSX/WO/2RaNH0+iILFLkcM5K550Xw58exnDf9PoVkLP1qGUBiUlwLKoierA5jGY1AZA48tAsQ83AYNUHF2CJcLeyJHbGdmleFFYOu39Or48PazZAVXfvxOCfCiMMNvGVEPo4/+GkKyA2nioPZ/Pa2AhMMnNvJ36ey7yVI76E28zZTQqd4eqV1C+ipyiBG0Qo3zuCYSs6rQ/e+wxFU/UQxdF1PGthwXLoVa9ZVTcozypJnYVfHlugFIX0YvITFudWr1NuYMmYLXxSBpK1oyACgovOC95pp1eU2nyGwu2htE0a77eSx3+tphkmkNT+HTSQe629fzw/cxEYo=
    distributions: sdist
    on:
      tags: true
    skip_cleanup: true
