language: python
cache: pip
python:
  - 3.6
sudo: required
before_script:
  - "herbstluftwm &"
  - sleep 1
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb herbstluftwm
  - sudo apt-get install libsqlite3-dev
  - sudo apt-get install build-essential
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update --yes -q conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
  - conda config --add channels conda-forge
install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - sleep 3
  - conda install -q python=$TRAVIS_PYTHON_VERSION
    anaconda-client==1.7.2
    brotlipy==0.7.0
    ca-certificates==2020.12.5
    certifi==2020.12.5
    cffi==1.14.5
    conda-build==3.21.4
    conda==4.10.0
    cryptography==3.4.7
    cython==0.29.17
    jinja2==2.11.3
    ncurses==6.2
    peewee==3.14.4
    pip==21.0.1
    pyopenssl==20.0.1
    pyparsing==2.4.7
    pytest==4.6.3
    pytz==2021.1
    readline==8.1
    requests==2.25.1
    setuptools==49.6.0
    urllib3==1.26.4
    wheel==0.36.2
  - pip install "Cython==0.29.17"
  - pip install 'peewee==3.14.4'
  - pip install -r requirements.txt
  - pip install codecov 'coverage==4.3' codeclimate-test-reporter
script:
  - coverage run -m pytest --ignore=decide/qt
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - CODECLIMATE_REPO_TOKEN=38338f4be02599584d9d3672ed50c25ca2b24c0a9565bfbb000e6a1389f13700
    codeclimate-test-reporter
  - chmod +x ./deploy_anaconda.sh
deploy:
  - provider: script
    script: "./deploy_anaconda.sh"
    on:
      tags: true
    skip_cleanup: true
  - provider: pypi
    user: jelmert
    password:
      secure: fmCoyxAZjjMM231CWnHqH3sbccEtBOklO00zztQXdHuNLkN0qk6jfkuU1CUD663tVPV75PCkhtr8CAXPTZ9vRR9gai3B4+IaJWUowdEL/c8wj7iilEixRlG2IdnXrI61dz/tMgRtq3pEzwDmdCvTfJaOUK2aAtocMKOC+74N/xh66sOCijbXBBdEE2x1tYjw1DhhoymHgAfYUjRU4rBKjSCrF3ZakeWGFhNeD66g/LzJh30MfT4Zzs5xHCEsRayVeKfYlBpmlvUOE+loPwdulGKEg2hYmOR566tKgYc0XGqlhepMIeFWMDwAyoXbsg9frTiVWgL3jdtIXQ2uQ7TqKjK8sIy28XFSX/WO/2RaNH0+iILFLkcM5K550Xw58exnDf9PoVkLP1qGUBiUlwLKoierA5jGY1AZA48tAsQ83AYNUHF2CJcLeyJHbGdmleFFYOu39Or48PazZAVXfvxOCfCiMMNvGVEPo4/+GkKyA2nioPZ/Pa2AhMMnNvJ36ey7yVI76E28zZTQqd4eqV1C+ipyiBG0Qo3zuCYSs6rQ/e+wxFU/UQxdF1PGthwXLoVa9ZVTcozypJnYVfHlugFIX0YvITFudWr1NuYMmYLXxSBpK1oyACgovOC95pp1eU2nyGwu2htE0a77eSx3+tphkmkNT+HTSQe629fzw/cxEYo=
    distributions: sdist
    on:
      tags: true
    skip_cleanup: true
