language: python
python:
  - "3.5"
# command to run tests
install:
  - pip install codecov coverage codeclimate-test-reporter
script: nosetests --with-coverage --cover-erase
after_success:
  - coverage
  - bash <(curl -s https://codecov.io/bash)
  - CODECLIMATE_REPO_TOKEN=<a31fdc6d118fc38068ae49f3bd34ef64b76323064955180ac8a5be01599075b5> codeclimate-test-reporter

