language: python
cache: pip
python:
  - "3.6"
# command to run tests
install:
  - pip install codecov coverage codeclimate-test-reporter nose-exclude
  - pip install -r requirements.txt
script: nosetests --with-coverage --cover-erase --exclude-test=decide.model.helpers.test.test_database.TestHashFunctions
after_success:
  - coverage
  - bash <(curl -s https://codecov.io/bash)
  - CODECLIMATE_REPO_TOKEN=a31fdc6d118fc38068ae49f3bd34ef64b76323064955180ac8a5be01599075b5 codeclimate-test-reporter

