language: python
cache: pip
python:
  - "3.6"
# command to run tests
install:
  - pip install codecov 'coverage==4.3' codeclimate-test-reporter
  - pip install -r requirements.txt
script: nosetests --with-coverage --cover-erase --cover-package=decide --cover-inclusive
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - CODECLIMATE_REPO_TOKEN=38338f4be02599584d9d3672ed50c25ca2b24c0a9565bfbb000e6a1389f13700 codeclimate-test-reporter

