{% set data = load_setup_py_data() %}

package:
  name: 'decide-exchange-model'
  version: {{ data.get('version') }}

#source:
#  git_rev: master
#  git_url: https://github.com/foarsitter/decide-exchange-model.git

source:
  path: ./

build:
  number: 0
  entry_points:
    - decide-cli=decide.cli:main
    - decide-gui=decide.gui:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python==3.6.7
    - setuptools==49.6.0
  run:
    - python==3.6.7
    - anaconda-client==1.7.2
    - brotlipy==0.7.0
    - ca-certificates==2020.12.5
    - certifi==2020.12.5
    - cffi==1.14.5
    - conda-build==3.21.4
    - conda==4.10.0
    - cryptography==3.4.7
    - cython==0.29.17
    - jinja2==2.11.3
    - ncurses==6.2
    - peewee==3.14.4
    - pip==21.0.1
    - pyopenssl==20.0.1
    - pyparsing==2.4.7
    - pytest==4.6.3
    - python=3.6.7
    - pytz==2021.1
    - readline==8.1
    - requests==2.25.1
    - setuptools==49.6.0
    - urllib3==1.26.4
    - wheel==0.36.2
test:
  imports:
    - decide
    - decide.qt
    - decide.model
    - decide.model.observers
    - decide.model.test


about:
  home: https://github.com/foarsitter/decide-exchange-model
  license: GPL-3.0
  license_family: GPL3
  license_file: 'LICENSE'
  summary: Decide exchange model
  description: 'Decide exchange model for collective decision-making'
  doc_url: ''
  dev_url: 'https://github.com/foarsitter/decide-exchange-model'

app:
  entry: decide-gui