{% set name = "decide-exchange-model" %}
{% set version = "1.0rc6" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "bed20d0a897875514347efb9a94ee446ea152276ef99f05ea15582772a565e14" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_rev: master
  git_url: https://github.com/foarsitter/decide-exchange-model.git
#  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
#  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - decide-cli=decide.cli:main
    - decide-gui=decide.gui:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - matplotlib
    - numpy
    - pandas
    - peewee

test:
  imports:
    - decide
    - decide.model
    - decide.model.helpers
    - decide.model.helpers.test
    - decide.model.observers
    - decide.model.test


about:
  home: https://github.com/foarsitter/decide-exchange-model
  license: GPL-3.0
  license_family: GPL3
  license_file: 'LICENSE'
  summary: Decide exchange model
  description: 'Decide exchange model for collective decision-making



    '
  doc_url: ''
  dev_url: 'https://github.com/foarsitter/decide-exchange-model'

