package:
  name: 'decide-exchange-model'
  version: '2022.1.27'

source:
  path: ./

build:
  number: 0
  entry_points:
    - decide-cli=decide.cli:main
    - decide-gui=decide.gui:main
  osx_is_app: true
  script: "$PYTHON -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - poetry
    - python
    - pip
    - setuptools
  run:
    - python
    - pyqt >=5.10,<5.16
    - setuptools >=49.6.0
    - blinker >=1.5
    - matplotlib >=3.6.0
    - numpy >=1.23.4
    - pandas >=1.5.2,<2.0
    - peewee >=3.14.4
    - typesystem ==0.2.2
    - python.app  # [osx]
test:
  imports:
    - decide
    - decide.data
    - decide.data.tests
    - decide.model
    - decide.model.observers
    - decide.model.observers.tests
    - decide.model.test
    - decide.qt
    - decide.qt.inputwindow
    - decide.qt.inputwindow.tests
    - decide.qt.mainwindow
    - decide.qt.mainwindow.tests
    - decide.results
    - decide.tests
  commands:
    - decide-cli --help

about:
  home: https://github.com/foarsitter/decide-exchange-model
  license: GPL-3.0
  license_family: GPL3
  license_file: 'LICENSE'
  summary: Decide exchange model
  description: 'Decide exchange model for collective decision-making'
  doc_url: ''
  dev_url: 'https://github.com/foarsitter/decide-exchange-model'

app:
  entry: decide-gui