{% set data = load_setup_py_data() %}

package:
  name: 'decide-exchange-model'
  version: {{ data.get('version') }}

#source:
#  git_rev: master
#  git_url: https://github.com/foarsitter/decide-exchange-model.git

source:
  path: ./

build:
  number: 0
  entry_points:
    - decide-cli=decide.cli:main
    - decide-gui=decide.gui:main

about:
  home: https://github.com/foarsitter/decide-exchange-model
  license: GPL-3.0
  license_family: GPL3
  license_file: 'LICENSE'
  summary: Decide exchange model
  description: 'Decide exchange model for collective decision-making'
  doc_url: ''
  dev_url: 'https://github.com/foarsitter/decide-exchange-model'

app:
  entry: decide-gui