name: Publish to Anaconda

on:
  release:
    types: [created]

jobs:
  anaconda:
    name: Publish to Anaconda
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: /usr/share/miniconda3/envs/decide
          key: decide-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
        id: cache
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          channels: conda-forge
          conda-build-version: 'latest'
          conda-solver: 'libmamba'
          channel-priority: strict
          activate-environment: "decide"
      - run: |
          conda install --yes anaconda-client
          conda build .
          conda convert --platform all /usr/share/miniconda/conda-bld/linux-64/decide-exchange-model-*.tar.bz2 --output-dir /usr/share/miniconda/conda-bld/
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload /usr/share/miniconda/conda-bld/**/decide-exchange-model-*.tar.bz2