name: Publish to Anaconda

on:
  release:
    types: [created]

jobs:
  anaconda:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
            - '3.9'
            - '3.10'
            - '3.11'
    name: Publish to Anaconda
    steps:
      - uses: actions/checkout@v2
        id: cache
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          conda-build-version: '3.28'
          conda-solver: 'libmamba'
          channel-priority: strict
          activate-environment: "decide"
      - run: |
          conda install --yes anaconda-client
          conda build .
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload /usr/share/miniconda/conda-bld/**/decide-exchange-model-*.tar.bz2