name: Publish to Anaconda

on:
  release:
    types: [ created ]

jobs:
  anaconda:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest,
        ]
        python-version: [
          '3.9',
          '3.10',
          '3.11',
        ]
    name: Publish to Anaconda
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        id: cache
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
          conda-build-version: '3.28'
          conda-solver: 'libmamba'
          activate-environment: "decide"
      - run: |
          conda install --yes anaconda-client
          anaconda --version
          conda build --numpy 1.23.4 --python ${{ matrix.python-version }} .
#          conda convert --platform all /usr/share/miniconda/conda-bld/linux-64/decide-exchange-model-*.tar.bz2 --output-dir /usr/share/miniconda/conda-bld/
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload /usr/share/miniconda/conda-bld/**/decide-exchange-model-*.tar.bz2